version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=PaoRO
      - PGHOST=db
      - PGPASSWORD=telepass
      - PGDATABASE=tele
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /server
    command: bash -c "npm install && npm start"

  db:
    image: postgres:12-alpine
    ports:
      - 35432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro"
    environment: 
      - POSTGRES_DB=tele
      - POSTGRES_USER=PaoRO
      - POSTGRES_PASSWORD=telepass
volumes:
  dbdata: